// ─── USERS ──────────────────────────────────────────────────────────────────
export const USERS = [
  { id: 1, name: "Jordan Mills", initials: "JM", role: "tac", territory: "Southeast", email: "jordan.mills@medtronic.com", password: "tac123" },
  { id: 2, name: "Taylor Brooks", initials: "TB", role: "tac", territory: "Southeast", email: "taylor.brooks@medtronic.com", password: "tac123" },
  { id: 3, name: "Casey Rivera", initials: "CR", role: "tac", territory: "Southeast", email: "casey.rivera@medtronic.com", password: "tac123" },
  { id: 4, name: "Morgan Lee", initials: "ML", role: "tac", territory: "Southeast", email: "morgan.lee@medtronic.com", password: "tac123" },
  { id: 5, name: "Sarah Thompson", initials: "ST", role: "manager", territory: "Southeast Region", email: "sarah.thompson@medtronic.com", password: "mgr123" },
];

// ─── JOURNEY ────────────────────────────────────────────────────────────────
export const JOURNEY_STAGES = ["Awareness", "Education", "Consideration", "Adoption"];

export const STAGE_CONFIG = {
  Awareness: {
    color: "yellow",
    textColor: "text-yellow-400",
    bgColor: "bg-yellow-400/10",
    borderColor: "border-yellow-400/20",
    behavior: "CONNECT",
    goal: "Spark curiosity, create psychological safety, and open the door to future conversations",
    hcpMindset: [
      "I manage pain conservatively via pills & creams",
      "Referral feels extreme or unnecessary",
      "Surgery is too dangerous",
      "I don't know much about SCS",
    ],
    tacActions: [
      "Use curiosity hook (data, patient story, or case-share why it matters)",
      "Ask 2–3 open-ended questions",
      "Learn practice basics",
      "Listen for pain points & challenges",
    ],
    conversationStarters: [
      "How do you currently manage patients who don't respond to conservative care?",
      "What happens for the patients who are still suffering in pain after trying pills or creams?",
      "What percentage of your patients would you say have ongoing pain after conservative treatment?",
    ],
    microCommitment: "Get welcomed back. Gain agreement from HCP to learn more.",
    assets: [
      { name: "SCS Podiatry Referral Brochure", code: "UC202401456 EN", type: "brochure" },
      { name: "SCS for DPN HCP 1 Pager", code: "UC202302354B EN", type: "pager" },
    ],
    rolePlayPrompt: "You are a skeptical, busy podiatrist who manages pain conservatively. You are comfortable with your current approach and initially resistant to hearing about new therapies. You have 5 minutes. Be realistic but not impossible.",
  },
  Education: {
    color: "cyan",
    textColor: "text-cyan-400",
    bgColor: "bg-cyan-400/10",
    borderColor: "border-cyan-400/20",
    behavior: "COLLABORATE",
    goal: "Build credibility and understanding through mutual exploration and shared learning",
    hcpMindset: [
      "Does this actually work?",
      "Is SCS safe for my patients?",
      "Show me evidence",
      "How does this compare to what I do now?",
    ],
    tacActions: [
      "Share clinical data. Ask 2–3 open-ended questions",
      "Provide peer-reviewed articles or summaries",
      "Use patient case stories for relatability",
      "Leave behind one-pager",
    ],
    conversationStarters: [
      "Can I share patient testimonial videos with you?",
      "Would it be helpful to see how a peer has successfully referred?",
      "What would success look like for your most challenging pain patient?",
      "What concerns or questions do you have about this approach?",
    ],
    microCommitment: "HCP accepts article, summary, agrees to attend clinical webinar, or reviews a success story.",
    assets: [
      { name: "SCS DPN HCP Clinical Evidence", code: "UC202215038D EN", type: "evidence" },
      { name: "Free CME Webinar – DPN Treatment Protocols", code: "CME-2025", type: "webinar" },
      { name: "MPI Clinical Data Summary", code: "MPI-2024", type: "summary" },
    ],
    rolePlayPrompt: "You are an interested but cautious HCP. You have specific questions about efficacy, safety, and how SCS compares to current standard of care. You challenge claims and want to see real evidence before you believe anything.",
  },
  Consideration: {
    color: "pink",
    textColor: "text-pink-400",
    bgColor: "bg-pink-400/10",
    borderColor: "border-pink-400/20",
    behavior: "CLARIFY",
    goal: "Deepen understanding of specific patient needs and practice logistics to evaluate true fit",
    hcpMindset: [
      "Will my patients really accept this?",
      "Am I comfortable presenting this option to my patients?",
      "I don't want to risk my reputation",
      "Do my peers actually do this?",
    ],
    tacActions: [
      "Review specific patient scenarios",
      "Map referral steps. Use patient case stories for relatability",
      "Identify & remove barriers",
      "Position referral as standard practice",
      "Provide helpful resources/assets",
    ],
    conversationStarters: [
      "How do you typically introduce new treatment options to your patients?",
      "Would you like to connect with a peer who's already referring?",
      "Now that you know there is a trial stage, how do you see this fitting for patients in your practice who may want to learn more?",
      "Are there one or two patients who come to mind that we could talk through?",
    ],
    microCommitment: "Agree to peer connection, Small HCP TAP, or identify one patient to refer.",
    assets: [
      { name: "Small HCP TAP", code: "TAP-S-2025", type: "tap" },
      { name: "Large HCP TAP", code: "TAP-L-2025", type: "tap" },
      { name: "Pain & Pod Best Practice Video", code: "VID-2025-01", type: "video" },
    ],
    rolePlayPrompt: "You are an HCP who is interested in SCS but has specific concerns about patient selection criteria and how this integrates into your practice workflow. You worry about your reputation and patient acceptance. You need practical answers.",
  },
  Adoption: {
    color: "green",
    textColor: "text-emerald-400",
    bgColor: "bg-emerald-400/10",
    borderColor: "border-emerald-400/20",
    behavior: "CLOSE",
    goal: "Support the first patient referral and establish ongoing product partnership for sustained adoption",
    hcpMindset: [
      "I'm ready to try this with the right patient",
      "Will this help more of my patients?",
      "What happens after I refer? Will I be supported?",
      "How will I know if this is working?",
    ],
    tacActions: [
      "Walk HCP through simple referral workflow",
      "Reinforce positive patient outcomes",
      "Recognize referral behavior",
      "Establish ongoing cadence. Provide ongoing support",
    ],
    conversationStarters: [
      "What would make you feel most confident about the first referral?",
      "How can I best support you and your patient through this process?",
      "What would success look like for you after the first few referrals?",
      "Is there anything preventing you from referring your first patient today?",
    ],
    microCommitment: "Make referring appropriate chronic pain patients a habit.",
    assets: [
      { name: "Patient TAP", code: "PTAP-2025", type: "tap" },
      { name: "Referral Workflow Guide", code: "REF-2025", type: "guide" },
      { name: "Back to the Things You Love Patient Materials", code: "UC-BTL-2024", type: "patient" },
    ],
    rolePlayPrompt: "You are an HCP who believes in SCS and has a patient in mind, but needs confidence the referral process is clear and easy. You have logistical concerns about what happens after you refer and whether your patient will be supported.",
  },
};

// ─── HCP DATA ────────────────────────────────────────────────────────────────
export const INITIAL_HCPS = [
  {
    id: 1,
    name: "Dr. Sandra Reyes",
    specialty: "Podiatrist",
    practice: "Atlanta Foot & Ankle Center",
    address: "1234 Peachtree St, Atlanta, GA 30309",
    phone: "(404) 555-0182",
    email: "s.reyes@atlantafoot.com",
    stage: "Education",
    style: "Evidence-Driven",
    patientVolume: "High",
    dpnCaseMix: "High",
    currentlyReferring: false,
    yearsInPractice: 14,
    groupPractice: true,
    lastVisit: "Feb 14, 2026",
    nextVisit: "Feb 28, 2026",
    notes: "Interested in DPN clinical data. Asked about trial process. Has a patient population that could benefit.",
    objections: ["Unsure about patient selection criteria", "Wants to see more real-world outcomes data"],
    visits: [
      { date: "Feb 14, 2026", stage: "Education", outcome: "Shared CME webinar info. HCP agreed to attend.", commitment: "Attending webinar Mar 3" },
      { date: "Jan 28, 2026", stage: "Awareness", outcome: "Initial visit. Good rapport. Curious about SCS for DPN.", commitment: "Agreed to follow-up meeting" },
    ],
    tacId: 1,
  },
  {
    id: 2,
    name: "Dr. Marcus Webb",
    specialty: "PCP",
    practice: "Warm Springs Family Medicine",
    address: "88 Broad St, Warm Springs, GA 31830",
    phone: "(706) 555-0247",
    email: "m.webb@wsfamilymed.com",
    stage: "Awareness",
    style: "Relationship-Driven",
    patientVolume: "Medium",
    dpnCaseMix: "Medium",
    currentlyReferring: false,
    yearsInPractice: 8,
    groupPractice: false,
    lastVisit: "Feb 10, 2026",
    nextVisit: "Feb 24, 2026",
    notes: "New contact. Receptive to conversation. Manages many diabetic patients. Relationship-first approach works well.",
    objections: ["Doesn't know much about SCS", "Thinks referral might be extreme"],
    visits: [
      { date: "Feb 10, 2026", stage: "Awareness", outcome: "First visit. Used curiosity hook - asked about pain management gaps. Very receptive.", commitment: "Agreed to learn more next visit" },
    ],
    tacId: 1,
  },
  {
    id: 3,
    name: "Dr. Lisa Huang",
    specialty: "Endocrinologist",
    practice: "Meriwether Diabetes Center",
    address: "500 Medical Park Dr, Manchester, GA 31816",
    phone: "(706) 555-0391",
    email: "l.huang@meriwetherdiabetes.com",
    stage: "Consideration",
    style: "Peer-Influenced",
    patientVolume: "High",
    dpnCaseMix: "Very High",
    currentlyReferring: false,
    yearsInPractice: 11,
    groupPractice: true,
    lastVisit: "Feb 18, 2026",
    nextVisit: "Mar 4, 2026",
    notes: "Has 2-3 patients in mind. Wants to talk to a peer who has referred. Responds well to colleague testimonials.",
    objections: ["Worried about patient acceptance", "Reputation risk with colleagues"],
    visits: [
      { date: "Feb 18, 2026", stage: "Consideration", outcome: "Reviewed 2 specific patient scenarios. Excited but cautious. Requested peer connection.", commitment: "Peer connection call scheduled" },
      { date: "Feb 3, 2026", stage: "Education", outcome: "Reviewed clinical evidence. Very interested in trial process.", commitment: "Accepted evidence summary" },
      { date: "Jan 15, 2026", stage: "Awareness", outcome: "Introduced SCS concept. Strong interest given patient population.", commitment: "Agreed to second meeting" },
    ],
    tacId: 1,
  },
  {
    id: 4,
    name: "Dr. James Okafor",
    specialty: "Podiatrist",
    practice: "Manchester Podiatry Group",
    address: "210 Commerce Ave, Manchester, GA 31816",
    phone: "(706) 555-0512",
    email: "j.okafor@manchesterpod.com",
    stage: "Adoption",
    style: "Efficiency-Focused",
    patientVolume: "Very High",
    dpnCaseMix: "High",
    currentlyReferring: true,
    yearsInPractice: 19,
    groupPractice: true,
    lastVisit: "Feb 19, 2026",
    nextVisit: "Mar 5, 2026",
    notes: "First referral made Feb 19. Needs process to be smooth for his staff. Strong advocate once committed.",
    objections: ["Wants process to be simple for his staff"],
    visits: [
      { date: "Feb 19, 2026", stage: "Adoption", outcome: "First referral submitted! Walked through workflow with staff. Very positive.", commitment: "Will refer next appropriate patient" },
      { date: "Feb 5, 2026", stage: "Consideration", outcome: "Identified first candidate patient. Mapped referral steps together.", commitment: "Committed to first referral" },
    ],
    tacId: 1,
  },
  {
    id: 5,
    name: "Dr. Patricia Kim",
    specialty: "Endocrinologist",
    practice: "Atlanta Diabetes & Endocrine",
    address: "3400 Northside Pkwy, Atlanta, GA 30327",
    phone: "(404) 555-0678",
    email: "p.kim@atlantadiabetes.com",
    stage: "Awareness",
    style: "Evidence-Driven",
    patientVolume: "Very High",
    dpnCaseMix: "Very High",
    currentlyReferring: false,
    yearsInPractice: 22,
    groupPractice: true,
    lastVisit: "Feb 12, 2026",
    nextVisit: "Mar 1, 2026",
    notes: "Very busy practice. Skeptical but open. Wants rigorous evidence before any change in practice.",
    objections: ["High bar for clinical evidence", "Very limited time for rep visits"],
    visits: [
      { date: "Feb 12, 2026", stage: "Awareness", outcome: "Brief first visit. Interested but pressed for time. Will review brochure.", commitment: "Agreed to 20-min education visit" },
    ],
    tacId: 2,
  },
];

// ─── KNOWLEDGE MODULES ───────────────────────────────────────────────────────
export const KNOWLEDGE_MODULES = [
  {
    id: 1,
    title: "Diabetic Peripheral Neuropathy: Disease State Overview",
    stage: "Awareness",
    duration: "8 min",
    description: "Understanding DPN progression, patient impact, and why conservative care often falls short for chronic pain patients.",
    content: [
      { type: "text", heading: "What is Diabetic Peripheral Neuropathy?", body: "Diabetic peripheral neuropathy (DPN) is nerve damage caused by diabetes, typically affecting the feet and legs. It affects approximately 50% of people with diabetes and is a leading cause of chronic pain and disability." },
      { type: "stat", value: "50%", label: "of diabetic patients develop DPN" },
      { type: "stat", value: "~26M", label: "Americans have diabetes-related neuropathy" },
      { type: "text", heading: "Why Conservative Care Falls Short", body: "Medications like gabapentin, duloxetine, and pregabalin provide only partial relief for many patients. Studies show up to 60% of patients have inadequate pain control with current pharmacological options, leaving a significant unmet need." },
      { type: "key_point", text: "When speaking with podiatrists or PCPs: Ask how many of their DPN patients are still in pain despite current treatment. This opens the door to SCS as an option for that specific population." },
    ],
    quiz: [
      { q: "What percentage of diabetic patients develop DPN?", options: ["10%", "25%", "50%", "75%"], correct: 2 },
      { q: "Which of the following is NOT a first-line treatment for DPN?", options: ["Gabapentin", "Duloxetine", "Spinal Cord Stimulation", "Pregabalin"], correct: 2 },
      { q: "What is the primary message when a podiatrist says 'I manage pain with medications'?", options: ["Challenge their approach directly", "Acknowledge their approach and ask about patients still in pain", "Leave immediately", "Offer to replace their medications"], correct: 1 },
    ],
  },
  {
    id: 2,
    title: "Spinal Cord Stimulation: How It Works",
    stage: "Awareness",
    duration: "10 min",
    description: "Mechanism of action, the trial process, what patients experience, and why SCS is different from surgery.",
    content: [
      { type: "text", heading: "What is SCS?", body: "Spinal Cord Stimulation (SCS) is a minimally invasive, reversible therapy that delivers mild electrical pulses to the spinal cord to interrupt pain signals before they reach the brain. It is FDA-approved for chronic pain including diabetic peripheral neuropathy." },
      { type: "text", heading: "The Trial Process — A Key Differentiator", body: "Unlike surgery, SCS begins with a trial period of 5-10 days. The patient tests the device before any permanent implant. This reversibility is often the most reassuring aspect for both patients and referring HCPs." },
      { type: "key_point", text: "Always lead with the trial process when addressing the 'surgery feels extreme' objection. The reversibility of SCS fundamentally changes how HCPs perceive the risk." },
      { type: "stat", value: "5-10", label: "day trial before permanent implant" },
      { type: "stat", value: "Reversible", label: "— no permanent commitment required for trial" },
    ],
    quiz: [
      { q: "What makes SCS different from traditional surgery in terms of patient commitment?", options: ["It costs less", "It has a reversible trial period", "It requires no anesthesia", "It is done in an office"], correct: 1 },
      { q: "How long is the typical SCS trial period?", options: ["1-2 days", "5-10 days", "30 days", "3 months"], correct: 1 },
      { q: "When a podiatrist says 'surgery is too dangerous for my patients,' the best response is to:", options: ["Agree and leave", "Explain SCS is not traditional surgery and lead with the trial process", "Argue that surgery is safe", "Change the subject"], correct: 1 },
    ],
  },
  {
    id: 3,
    title: "Clinical Evidence for SCS in DPN",
    stage: "Education",
    duration: "12 min",
    description: "Key clinical trials, evidence summaries, and how to present data compliantly within approved messaging.",
    content: [
      { type: "text", heading: "The Evidence Base", body: "Multiple randomized controlled trials have demonstrated the effectiveness of SCS for DPN. The SENZA-PDN trial is a landmark study showing significant and sustained pain relief compared to conventional medical management." },
      { type: "key_point", text: "COMPLIANCE NOTE: Always reference only approved clinical data from your MRL-approved assets (UC202215038D EN). Never make efficacy claims beyond what is in approved materials." },
      { type: "text", heading: "Presenting Evidence Collaboratively", body: "At the Education stage, your role is to collaborate — not lecture. Share data, then ask questions. 'I wanted to share this evidence summary — what questions does this raise for you?' invites dialogue rather than resistance." },
      { type: "stat", value: "SENZA-PDN", label: "Landmark randomized controlled trial" },
    ],
    quiz: [
      { q: "What is the correct approach when sharing clinical data with a skeptical HCP?", options: ["Present all data quickly and leave", "Share data and immediately ask a follow-up question to invite dialogue", "Defend every data point aggressively", "Only share positive outcomes"], correct: 1 },
      { q: "Which approved asset contains clinical evidence for SCS in DPN?", options: ["UC202401456 EN", "UC202215038D EN", "UC202302354B EN", "TAP-S-2025"], correct: 1 },
      { q: "When an HCP challenges a clinical claim, the best TAC response is:", options: ["Repeat the claim louder", "Acknowledge their question, refer to approved data, and invite their perspective", "Dismiss their concern", "Leave the data and move on"], correct: 1 },
    ],
  },
  {
    id: 4,
    title: "Patient Identification Criteria",
    stage: "Consideration",
    duration: "7 min",
    description: "Who is an appropriate SCS candidate and how to help HCPs identify the right patients in their practice.",
    content: [
      { type: "text", heading: "The Ideal SCS Candidate", body: "Appropriate patients typically include those with: (1) Chronic pain lasting 3+ months despite conservative treatment, (2) DPN with inadequate pain control on medications, (3) No contraindications to implant, (4) Psychological clearance, (5) Motivated to improve quality of life." },
      { type: "key_point", text: "At the Consideration stage, help the HCP visualize specific patients in their practice. Ask: 'When you think of your most challenging pain patient right now — who comes to mind?' This makes the concept personal and actionable." },
      { type: "text", heading: "Contraindications to Be Aware Of", body: "Patients with active infection, coagulopathy, cardiac pacemakers (depending on type), or who are pregnant are generally not candidates. Always defer specific clinical judgment to the implanting physician." },
    ],
    quiz: [
      { q: "Which patient profile is typically most appropriate for SCS consideration?", options: ["New onset pain, first month", "Chronic pain 3+ months with inadequate response to conservative care", "Any patient with diabetes", "Patients who prefer to avoid all treatment"], correct: 1 },
      { q: "When helping an HCP identify candidates, the most effective approach is:", options: ["Give them a general list and leave", "Ask them to think of a specific challenging patient in their practice", "Tell them all their patients qualify", "Focus only on contraindications"], correct: 1 },
      { q: "Who makes the final determination on patient appropriateness for SCS?", options: ["The TAC", "The referring HCP", "The implanting physician after full evaluation", "The insurance company"], correct: 2 },
    ],
  },
  {
    id: 5,
    title: "Navigating the Referral Pathway",
    stage: "Adoption",
    duration: "6 min",
    description: "Step-by-step referral process, what happens post-referral, and how to support the HCP and patient through the journey.",
    content: [
      { type: "text", heading: "The Referral Process — Step by Step", body: "Step 1: HCP identifies appropriate patient. Step 2: HCP or staff completes referral form. Step 3: Patient contacts specialty practice (Medtronic can support). Step 4: Evaluation appointment scheduled. Step 5: Trial planned if appropriate. Step 6: Feedback loop back to referring HCP." },
      { type: "key_point", text: "The most common barrier at Adoption is uncertainty about what happens after the referral. Close this gap by walking through each step clearly and offering to be the bridge between the referring HCP and the specialty team." },
      { type: "text", heading: "Your Role Post-Referral", body: "You are the relationship owner. Follow up with the referring HCP after the referral is made. Share outcomes when possible. Celebrate the first referral. This reinforces the behavior and builds habit." },
      { type: "stat", value: "1st Referral", label: "is the hardest — your job is to make it easy" },
    ],
    quiz: [
      { q: "What is the most common barrier at the Adoption stage?", options: ["The HCP doesn't believe in SCS", "Uncertainty about what happens after the referral is made", "No appropriate patients exist", "Cost concerns"], correct: 1 },
      { q: "After a referral is made, the TAC's next action should be:", options: ["Move on to the next HCP", "Follow up with the referring HCP and close the feedback loop", "Wait for the patient to call", "Do nothing — the job is done"], correct: 1 },
      { q: "The best way to build referral habit is to:", options: ["Pressure the HCP weekly", "Celebrate the first referral and reinforce the positive outcome", "Remind them of their commitment constantly", "Increase visit frequency"], correct: 1 },
    ],
  },
];

// ─── ROLE PLAYS ──────────────────────────────────────────────────────────────
export const ROLE_PLAYS = [
  {
    id: 1,
    title: "Skeptical Podiatrist – First Visit",
    stage: "Awareness",
    scenario: "Dr. Smith is a busy podiatrist who manages pain conservatively with medications and creams. She's skeptical of new therapies, has 5 minutes, and is comfortable with her current approach.",
    objective: "Use connect behaviors and a curiosity hook to open the conversation and earn the HCP's attention and interest.",
    scoringCriteria: ["Opens with curiosity hook", "Asks 2+ open-ended questions", "Listens without immediately pitching", "Earns a micro-commitment for follow-up"],
  },
  {
    id: 2,
    title: "Evidence-Challenger – Education Stage",
    stage: "Education",
    scenario: "Dr. Patel is interested but cautious. He has specific questions about efficacy and safety, challenges every claim, and wants to know how SCS compares to current standard of care.",
    objective: "Bring relevant evidence, answer questions transparently, co-explore the treatment's fit, and invite their clinical expertise.",
    scoringCriteria: ["References only approved clinical data", "Answers transparently rather than defensively", "Invites HCP's clinical perspective", "Secures agreement on next educational step"],
  },
  {
    id: 3,
    title: "Reputation-Worried HCP – Consideration Stage",
    stage: "Consideration",
    scenario: "Dr. Garcia is interested in SCS but worried about how her patients will react and what her peers will think. She needs reassurance from peers before she'll act.",
    objective: "Apply clarify behaviors. Get specific about patient scenarios, map implementation steps, and address reputation concerns.",
    scoringCriteria: ["Acknowledges reputation concern empathetically", "Uses peer evidence or offers peer connection", "Reviews a specific patient scenario", "Secures agreement on peer call or first patient identification"],
  },
  {
    id: 4,
    title: "Ready to Refer – Needs Process Clarity",
    stage: "Adoption",
    scenario: "Dr. Johnson believes in SCS and has a patient in mind, but needs the referral workflow to be crystal clear before committing. He's worried about his staff being confused.",
    objective: "Apply close behaviors. Walk through the referral pathway clearly, address hesitations, and secure the first referral commitment.",
    scoringCriteria: ["Clearly maps each referral step", "Proactively addresses staff workflow concern", "Offers post-referral support commitment", "Secures explicit referral commitment"],
  },
];

// ─── TEAM DATA (for Manager) ─────────────────────────────────────────────────
export const TEAM_PROGRESS = [
  {
    tacId: 1,
    name: "Jordan Mills",
    initials: "JM",
    modulesCompleted: 3,
    totalModules: 5,
    rolePlaysCompleted: 2,
    avgScore: 88,
    hcpCount: 4,
    referralsThisMonth: 3,
    flagged: false,
    recentActivity: "Completed Education module. High scorer on role-play.",
    pendingReviews: [
      {
        id: 101,
        rolePlayTitle: "Evidence-Challenger – Education Stage",
        date: "Feb 19, 2026",
        score: 88,
        hasVideo: true,
        transcript: [
          { role: "HCP", text: "Look, I've heard about SCS before but I'm skeptical. What evidence do you have that this actually works for my DPN patients?" },
          { role: "TAC", text: "That's exactly the right question to ask, Dr. Patel. I brought our clinical evidence summary today — the SENZA-PDN trial showed significant sustained pain relief compared to conventional medical management. Can I walk you through the key findings?" },
          { role: "HCP", text: "How significant? Give me numbers." },
          { role: "TAC", text: "The data is in this approved summary (UC202215038D EN) — I want to make sure I'm referencing it accurately for you. What would you most want to see — efficacy outcomes or the safety profile first?" },
          { role: "HCP", text: "Efficacy. If it doesn't work, safety doesn't matter." },
          { role: "TAC", text: "Fair point. Let me show you the primary endpoint data. And I'd love your clinical read on this — does this population look like patients you're managing today?" },
        ],
        coachingNotes: "",
      },
    ],
  },
  {
    tacId: 2,
    name: "Taylor Brooks",
    initials: "TB",
    modulesCompleted: 2,
    totalModules: 5,
    rolePlaysCompleted: 1,
    avgScore: 74,
    hcpCount: 3,
    referralsThisMonth: 1,
    flagged: false,
    recentActivity: "Completed Awareness module. Needs coaching on handling evidence challenges.",
    pendingReviews: [
      {
        id: 102,
        rolePlayTitle: "Skeptical Podiatrist – First Visit",
        date: "Feb 18, 2026",
        score: 74,
        hasVideo: true,
        transcript: [
          { role: "HCP", text: "I only have a few minutes. What do you want?" },
          { role: "TAC", text: "I appreciate your time. I work with Medtronic Neuromodulation — I wanted to ask you a quick question. How do you currently handle the patients in your practice who are still in pain after conservative treatment?" },
          { role: "HCP", text: "I adjust their medications. That's standard of care." },
          { role: "TAC", text: "Makes sense. And for those who still don't respond adequately — what options do you have for them at that point?" },
          { role: "HCP", text: "I mean... not many good ones honestly." },
          { role: "TAC", text: "That's exactly why I wanted to connect with you. There's a therapy that's showing strong results specifically for those patients. Can I come back and share some information at a time that works better for you?" },
        ],
        coachingNotes: "",
      },
    ],
  },
  {
    tacId: 3,
    name: "Casey Rivera",
    initials: "CR",
    modulesCompleted: 0,
    totalModules: 5,
    rolePlaysCompleted: 0,
    avgScore: null,
    hcpCount: 2,
    referralsThisMonth: 0,
    flagged: true,
    recentActivity: "No knowledge modules or role-plays completed. Recommend immediate coaching conversation.",
    pendingReviews: [],
  },
  {
    tacId: 4,
    name: "Morgan Lee",
    initials: "ML",
    modulesCompleted: 4,
    totalModules: 5,
    rolePlaysCompleted: 3,
    avgScore: 91,
    hcpCount: 5,
    referralsThisMonth: 4,
    flagged: false,
    recentActivity: "Top performer. Highest referral count this month.",
    pendingReviews: [],
  },
];
